using Dapper;

namespace eCommerce.Api.Database;

public static class DatabaseInitializer
{
    public static async Task InitializeAsync(this WebApplication app)
    {
        await using var scope = app.Services.CreateAsyncScope();
        var context = scope.ServiceProvider.GetRequiredService<ApplicationDbContext>();
        using var connection = context.CreateConnection();

        const string sql = @"
            CREATE TABLE IF NOT EXISTS public.""OrderPayments""
            (
                ""OrderPaymentId"" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                ""OrderId"" INTEGER NOT NULL,
                ""Provider"" VARCHAR(50) NOT NULL,
                ""ProviderOrderId"" VARCHAR(100),
                ""ProviderCaptureId"" VARCHAR(100),
                ""Currency"" VARCHAR(10) NOT NULL,
                ""Amount"" NUMERIC(18, 2) NOT NULL,
                ""Status"" VARCHAR(50) NOT NULL,
                ""ApprovalUrl"" TEXT,
                ""PayerEmail"" VARCHAR(255),
                ""LastWebhookEvent"" VARCHAR(120),
                ""RawCreateResponse"" TEXT,
                ""RawCaptureResponse"" TEXT,
                ""CreateDate"" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                ""UpdateDate"" TIMESTAMPTZ NULL,
                CONSTRAINT ""FK_OrderPayments_Orders_OrderId"" FOREIGN KEY (""OrderId"") REFERENCES public.""Orders""(""OrderId"") ON DELETE CASCADE
            );

            CREATE UNIQUE INDEX IF NOT EXISTS ""IX_OrderPayments_OrderId_Provider""
                ON public.""OrderPayments"" (""OrderId"", ""Provider"");

            CREATE UNIQUE INDEX IF NOT EXISTS ""IX_OrderPayments_ProviderOrderId""
                ON public.""OrderPayments"" (""ProviderOrderId"");

            CREATE TABLE IF NOT EXISTS public.""PayPalWebhookEvents""
            (
                ""PayPalWebhookEventId"" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                ""EventId"" VARCHAR(120),
                ""EventType"" VARCHAR(120),
                ""VerificationStatus"" VARCHAR(50) NOT NULL,
                ""ProviderOrderId"" VARCHAR(100),
                ""Payload"" TEXT NOT NULL,
                ""Headers"" TEXT,
                ""CreateDate"" TIMESTAMPTZ NOT NULL DEFAULT NOW()
            );

            CREATE UNIQUE INDEX IF NOT EXISTS ""IX_PayPalWebhookEvents_EventId""
                ON public.""PayPalWebhookEvents"" (""EventId"");";

        await connection.ExecuteAsync(sql);
    }
}
